// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://sukeytfjzxijvhdxbuen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_J5Wb3uCZRk78ySs5nElPkw_9RC4GLps";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
